apiVersion: v1
kind: BuildConfig
metadata:
  name: pd
spec:
  output:
    to:
      kind: ImageStreamTag
      name: pd:latest
  source:
    dockerfile : |-
      FROM openjdk:16-jdk
      MAINTAINER <roart@nvg.ntnu.no>
      RUN apt-get update && apt-get upgrade -y
      RUN apt-get install -y python3 python3-pip
      #RUN apt-get install -y postgresql-client-10
      RUN pip3 install pandas_datareader
      RUN mkdir /usr/local/pd
      ADD files/*.py /usr/local/pd/
      ADD files/*.jar /usr/local/pd/
      WORKDIR /usr/local/pd
      #ENV SPARK_MASTER_HOST 127.0.0.1
      CMD /usr/bin/python3 /usr/local/pd/generatexml.py; \
      	  /usr/bin/java -Dconnection.url=jdbc:postgresql://postgresql-10-centos7:5432/stockstat -jar /usr/local/pd/stockstat-input-0.6-SNAPSHOT-jar-with-dependencies.jar /tmp/nasdaq.xml; \
      	  echo finished; \
      	  while true; do sleep 3600; done
    images:
    - from: 
        kind: ImageStreamTag
        name: stockstat-build:latest
      paths: 
      - sourcePath: /opt/app-root/src/distribution/target/stockstat-distribution-0.6-SNAPSHOT-bin/stockstat-distribution-0.5-SNAPSHOT/lib/stockstat-input-0.5-SNAPSHOT-jar-with-dependencies.jar
        destinationDir: "files"
    - from: 
        kind: ImageStreamTag
        name: stockstat-build:latest
      paths: 
      - sourcePath: /opt/app-root/src/python/pd/datareader.py
        destinationDir: "files"
    - from: 
        kind: ImageStreamTag
        name: stockstat-build:latest
      paths: 
      - sourcePath: /opt/app-root/src/python/pd/flaskpdmain.py
        destinationDir: "files"
    - from: 
        kind: ImageStreamTag
        name: stockstat-build:latest
      paths: 
      - sourcePath: /opt/app-root/src/python/pd/generatexml.py
        destinationDir: "files"
    - from: 
        kind: ImageStreamTag
        name: stockstat-build:latest
      paths: 
      - sourcePath: /opt/app-root/src/python/pd/nasdaqsymbols.py
        destinationDir: "files"
  strategy:
    dockerStrategy:
      from: 
        kind: DockerImage
        name: openjdk:16-jdk
  triggers:
  - imageChange: {}
    type: ImageChange


