apiVersion: v1
kind: BuildConfig
metadata:
  name: spark
spec:
  output:
    to:
      kind: ImageStreamTag
      name: spark:latest
  source:
    dockerfile : |-
      FROM debian:stretch
      MAINTAINER <roart@nvg.ntnu.no>
      RUN apt-get update && apt-get upgrade -y
      RUN apt-get install -y openjdk-8-jdk curl procps
      RUN curl -s https://archive.apache.org/dist/spark/spark-2.3.0/spark-2.3.0-bin-hadoop2.7.tgz | tar -xz -C /usr/local
      WORKDIR /usr/local/spark-2.3.0-bin-hadoop2.7
      ENV SPARK_MASTER_HOST 127.0.0.1
      CMD /usr/local/spark-2.3.0-bin-hadoop2.7/sbin/start-master.sh --webui-port 8088; \
      /usr/local/spark-2.3.0-bin-hadoop2.7/sbin/start-slave.sh -c 1 -m 16G spark://0.0.0.0:7077; \
      while true; do sleep 3600; done
  strategy:
    dockerStrategy:
      from: 
        kind: DockerImage
        name: openjdk:8-jdk
  triggers:
  - imageChange: {}
    type: ImageChange


