apiVersion: v1
kind: BuildConfig
metadata:
  name: stockstat-iclij-core
spec:
  output:
    to:
      kind: ImageStreamTag
      name: stockstat-iclij-core:latest
  source:
    dockerfile : |-
      FROM openjdk:8-jdk
      MAINTAINER <roart@nvg.ntnu.no>
      ADD files/stockstat-iclij-core-0.5-SNAPSHOT.jar /usr/local/bin
      ADD files/iclij.xml /usr/local/config
      WORKDIR /usr/local/bin
      RUN ln -s /tmp /usr/local/logs
      CMD java -jar /usr/local/bin/stockstat-iclij-core-0.5-SNAPSHOT.jar
    images:
    - from: 
        kind: ImageStreamTag
        name: stockstat-build:latest
      paths: 
      - sourcePath: /opt/app-root/src/distribution/target/stockstat-distribution-0.5-SNAPSHOT-bin/stockstat-distribution-0.5-SNAPSHOT/lib/stockstat-iclij-core-0.5-SNAPSHOT.jar
        destinationDir: "files"
    - from: 
        kind: ImageStreamTag
        name: stockstat-build:latest
      paths: 
      - sourcePath: /opt/app-root/src/docker/iclij-core/iclij.xml
        destinationDir: "files"
  strategy:
    dockerStrategy:
      from: 
        kind: DockerImage
        name: openjdk:8-jdk
  triggers:
  - imageChange: {}
    type: ImageChange


