apiVersion: v1
kind: BuildConfig
metadata:
  name: stockstat-eureka
spec:
  output:
    to:
      kind: ImageStreamTag
      name: stockstat-eureka:latest
  source:
    dockerfile : |-
      FROM openjdk:8-jdk
      MAINTAINER <roart@nvg.ntnu.no>
      ADD files/stockstat-eureka-0.5-SNAPSHOT.jar /usr/local/bin
      WORKDIR /usr/local/bin
      RUN ln -s /tmp /usr/local/logs
      CMD java -jar /usr/local/bin/stockstat-eureka-0.5-SNAPSHOT.jar
    images:
    - from: 
        kind: ImageStreamTag
        name: stockstat-build:latest
      paths: 
      - sourcePath: /opt/app-root/src/distribution/target/stockstat-distribution-0.5-SNAPSHOT-bin/stockstat-distribution-0.5-SNAPSHOT/lib/stockstat-eureka-0.5-SNAPSHOT.jar
        destinationDir: "files"
  strategy:
    dockerStrategy:
      from: 
        kind: DockerImage
        name: openjdk:8-jdk
  triggers:
  - imageChange: {}
    type: ImageChange


