apiVersion: v1
kind: BuildConfig
metadata:
  name: stockstat-build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: stockstat-build:latest
  source:
    git:
      uri: https://github.com/rroart/stockstat#icli
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: wildfly:latest
        namespace: openshift
