apiVersion: v1
kind: BuildConfig
metadata:
  name: stockstat-iclij-web
spec:
  output:
    to:
      kind: ImageStreamTag
      name: stockstat-iclij-web:latest
  source:
    dockerfile : |-
      FROM openjdk:11-jdk
      MAINTAINER <roart@nvg.ntnu.no>
      ENV EUREKA_SERVER_URI http://stockstat-eureka:8761/eureka
      ADD files/stockstat-iclij-web-0.5-SNAPSHOT.war /usr/local/bin
      WORKDIR /usr/local/bin
      RUN ln -s /tmp /usr/local/logs
      EXPOSE 8181
      CMD java -Deureka.serviceUrl.default=http://stockstat-eureka:8761/eureka -jar /usr/local/bin/stockstat-iclij-web-0.5-SNAPSHOT.war
    images:
    - from: 
        kind: ImageStreamTag
        name: stockstat-build:latest
      paths: 
      - sourcePath: /opt/app-root/src/distribution/target/stockstat-distribution-0.5-SNAPSHOT-bin/stockstat-distribution-0.5-SNAPSHOT/lib/stockstat-iclij-web-0.5-SNAPSHOT.war
        destinationDir: "files"
  strategy:
    dockerStrategy:
      from: 
        kind: DockerImage
        name: openjdk:11-jdk
  triggers:
  - imageChange: {}
    type: ImageChange


