apiVersion: v1
kind: BuildConfig
metadata:
  name: stockstat-iclij-core
spec:
  output:
    to:
      kind: ImageStreamTag
      name: stockstat-iclij-core:latest
  source:
    dockerfile : |-
      FROM openjdk:16-jdk
      MAINTAINER <roart@nvg.ntnu.no>
      ENV EUREKA_SERVER_URI http://stockstat-eureka:8761/eureka
      ENV EUREKA_PREFER_IPADDRESS true
      ADD files/stockstat-iclij-core-0.6-SNAPSHOT.jar /usr/local/bin
      RUN mkdir /usr/local/conf
      ADD files/iclij.xml /usr/local/conf
      WORKDIR /usr/local/bin
      RUN ln -s /tmp /usr/local/logs
      CMD java -Deureka.serviceUrl.default=http://stockstat-eureka:8761/eureka -Dconnection.url=jdbc:postgresql://postgresql-10-centos7:5432/stockstat -jar /usr/local/bin/stockstat-iclij-core-0.6-SNAPSHOT.jar
    images:
    - from: 
        kind: ImageStreamTag
        name: stockstat-build:latest
      paths: 
      - sourcePath: /opt/app-root/src/distribution/target/stockstat-distribution-0.6-SNAPSHOT-bin/stockstat-distribution-0.5-SNAPSHOT/lib/stockstat-iclij-core-0.5-SNAPSHOT.jar
        destinationDir: "files"
    - from: 
        kind: ImageStreamTag
        name: stockstat-build:latest
      paths: 
      - sourcePath: /opt/app-root/src/docker/iclij-core/iclij.xml
        destinationDir: "files"
  strategy:
    dockerStrategy:
      from: 
        kind: DockerImage
        name: openjdk:16-jdk
  triggers:
  - imageChange: {}
    type: ImageChange


