apiVersion: v1
kind: BuildConfig
metadata:
  name: tensorflow
spec:
  output:
    to:
      kind: ImageStreamTag
      name: tensorflow:latest
  source:
    #contextDir : ./../../..//opt/app-root/src/docker/pd
    #dockerfilepath: docker/pd
    dockerfile : |-
      FROM debian:stretch
      MAINTAINER <roart@nvg.ntnu.no>
      RUN apt-get update && apt-get upgrade -y
      RUN apt-get install -y python3-pip
      RUN pip3 install tensorflow==1.5 pandas numpy Werkzeug Keras sklearn flask nameko
      ADD files/tensorflow/*.py /tmp/
      ADD files/tensorflow/*.sh /tmp/
      EXPOSE 8000
      WORKDIR /tmp
      CMD ./flasktf.sh
    images:
    - from: 
        kind: ImageStreamTag
        name: stockstat-build:latest
      paths: 
      - sourcePath: /opt/app-root/src/tensorflow
        destinationDir: "files"
#    - from: 
#        kind: ImageStreamTag
#        name: stockstat-build:latest
#      paths: 
#      - sourcePath: /opt/app-root/src/tensorflow/*.sh
#        destinationDir: "files"
  strategy:
    dockerStrategy:
      from: 
        kind: DockerImage
        name: openjdk:11-jdk
  triggers:
  - imageChange: {}
    type: ImageChange


