name: tf
channels:
  - pytorch
  - nvidia
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pip:
   - Flask
   - matplotlib
   - numpy
   - scikit_learn
   - torch
   - torchvision
   - Werkzeug
   - pretty_midi
