name: pt212
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cpu
    - torchvision==0.27
    - Flask
    - gdown
    - matplotlib
    - numpy
    - scikit_learn
    - torch
    - Werkzeug
    - cyclonedx-bom
    - pretty_midi
    - git+https://github.com/salu133445/muspy@main#egg=muspy
    - x-transformers==0.25.9    