package roart.config;

import java.util.HashMap;
import java.util.Map;
import roart.calculate.CalcMACDNode;

public class ConfigConstants {
    public static final String PROPFILE = "stockstat.prop";
    public static final String CONFIGFILE = "stockstat.xml";
   public static final String SPARK = "spark";
    public static final String HIBERNATE = "hibernate";
    public static final String SPARKMASTER = "sparkmaster";
    public static final String[] dbvalues = { HIBERNATE, SPARK };
    public static final String TENSORFLOW = "tensorflow";
    public static final String DATABASESPARK = "database.spark[@enable]";
    public static final String DATABASESPARKSPARKMASTER = "database.spark.sparkmaster";
    public static final String DATABASEHIBERNATE = "database.hibernate[@enable]";
    public static final String MACHINELEARNING = "machinelearning[@enable]";
    public static final String MACHINELEARNINGSPARKML = "machinelearning.sparkml[@enable]";
    public static final String MACHINELEARNINGSPARMMLSPARKMASTER = "machinelearning.sparkml.sparkmaster";
    public static final String MACHINELEARNINGSPARKMLMCP = "machinelearning.sparkml.mcp[@enable]";
    public static final String MACHINELEARNINGSPARKMLLR = "machinelearning.sparkml.lr[@enable]";
    public static final String MACHINELEARNINGTENSORFLOW = "machinelearning.tensorflow[@enable]";
    public static final String MACHINELEARNINGTENSORFLOWDNN = "machinelearning.tensorflow.dnn[@enable]";
    public static final String MACHINELEARNINGTENSORFLOWL = "machinelearning.tensorflow.l[@enable]";
    public static final String INDICATORS = "indicators[@enable]";
    public static final String INDICATORSMOVE = "indicators.move[@enable]";
    public static final String INDICATORSMACD = "indicators.macd[@enable]";
    public static final String INDICATORSMACDMACDHISTOGRAMDELTA = "indicators.macd.macdhistogramdelta[@enable]";
    public static final String INDICATORSMACDMACHHISTOGRAMDELTADAYS = "indicators.macd.macdhistogramdeltadays";
    
    public static final String  INDICATORSMACDMACDMOMENTUMDELTA = "indicators.macd.macdmomentumdelta[@enable]";
    public static final String INDICATORSMACDACDMOMENTUMDELTADAYS = "indicators.macd.macdmomentumdeltadays";
    public static final String  INDICATORSMACDRECOMMENDWEIGHTS = "indicators.macd.recommend[@enable]";
    public static final String  INDICATORSMACDRECOMMENDWEIGHTSBUYHISTOGRAM = "indicators.macd.recommend.weightbuyhistogram";
    public static final String  INDICATORSMACDRECOMMENDWEIGHTSBUYHISTOGRAMDELTA = "indicators.macd.recommend.weightbuyhistogramdelta";
    public static final String  INDICATORSMACDRECOMMENDWEIGHTSBUYMOMENTUM = "indicators.macd.recommend.weightbuymomemtum";
    public static final String  INDICATORSMACDRECOMMENDWEIGHTSBUGMOMENTUMDELTA = "indicators.macd.recommend.weightbuymomemtumdelta";
    public static final String  INDICATORSMACDRECOMMENDWEIGHTSSELLHISTOGRAM = "indicators.macd.recommend.weightsellhistogram";
    public static final String  INDICATORSMACDRECOMMENDWEIGHTSSELLHISTOGRAMDELTA = "indicators.macd.recommend.weightsellhistogramdelta";
    public static final String  INDICATORSMACDRECOMMENDWEIGHTSSELLMOMENTUM = "indicators.macd.recommend.weightsellmomemtum";
    public static final String INDICATORSMACDRECOMMENDWEIGHTSSELLMOMENTUMDELTA = "indicators.macd.recommend.weightsellmomemtumdelta";
    public static final String INDICATORSMACDMACHINELEARNING = "indicators.macd.machinelearning[@enable]";
    public static final String INDICATORSMACDMACHINELEARNINGMOMENTUMML = "indicators.macd.machinelearning.momemtumml[@enable]";
    public static final String INDICATORSMACDMACHINELEARNINGHISTOGRAMML = "indicators.macd.machinelearning.histogramml[@enable]";
    public static final String  INDICATORSMACDDAYSBEFOREZERO ="indicators.macd.daysbeforezero";
    public static final String  INDICATORSMACDDAYSAFTERZERO = "indicators.macd.daysafterzero";
    public static final String  INDICATORSRSI = "indicators.rsi[@enable]";
    public static final String  INDICATORSRSIDELTA = "indicators.rsi.rsidelta[@enable]";
    public static final String  INDICATORSRSIDELTADAYS = "indicators.rsi.rsideltadays";
    public static final String  INDICATORSSTOCHRSI = "indicators.stochrsi[@enable]";
    public static final String  INDICATORSSTOCHRSIDELTA = "indicators.stochrsi.stochrsidelta[@enable]";
    public static final String  INDICATORSSTOCHRSIDELTADAYS = "indicators.stochrsi.stochrsideltadays";
    public static final String  INDICATORSRSIRECOMMENDWEIGHTS = "indicators.rsi.recommend[@enable]";
    public static final String  INDICATORSRSIRECOMMENDWEIGHTSBUY = "indicators.rsi.recommend.weightbuy";
    public static final String  INDICATORSRSIRECOMMENDWEIGHTSBUYDELTA = "indicators.rsi.recommend.weightbuydelta";
    public static final String  INDICATORSRSIRECOMMENDWEIGHTSSELL = "indicators.rsi.recommend.weightsell";
    public static final String  INDICATORSRSIRECOMMENDWEIGHTSSELLDELTA = "indicators.rsi.recommend.weightselldelta";
    public static final String  INDICATORSCCI = "indicators.cci[@enable]";
    public static final String  INDICATORSCCIDELTA ="indicators.cci.ccidelta[@enable]";
    public static final String INDICATORSCCIDELTADAYS = "indicators.cci.ccideltadays";
    public static final String INDICATORSATR ="indicators.atr[@enable]";
    public static final String INDICATORSATRDELTA = "indicators.atr.atrdelta[@enable]";
    public static final String INDICATORSATRDELTADAYS = "indicators.atr.atrdeltadays";
    public static final String INDICATORSSTOCH = "indicators.stoch[@enable]";
    public static final String INDICATORSSTOCHSTOCHDELTA ="indicators.stoch.stochdelta[@enable]";
    public static final String INDICATORSSTOCHSTOCHDELTADAYS = "indicators.stoch.stochdeltadays";
    public static final String PREDICTORS = "predictors[@enable]";
    public static final String PREDICTORSLSTM = "predictors.lstm[@enable]";
    public static final String PREDICTORSLSTMWINDOWSIZE = "predictors.lstm.windowsize";
    public static final String PREDICTORSLSTMHORIZON = "predictors.lstm.horizon";
    public static final String PREDICTORSLSTMEPOCHS = "predictors.lstm.epochs";
    public static final String MISC = "misc";
    public static final String MISCPERCENTIZEPRICEINDEX = "misc.percentizepriceindex[@enable]";
    public static final String MISCMLSTATS = "misc.mlstats[@enable]";
    public static final String MISCOTHERSTATS = "misc.otherstats[@enable]";
    public static final String MISCMYDAYS = "misc.mydays";
    public static final String MISCMYTOPBOTTOM = "misc.mytopbottom";
    public static final String MISCMYTBLEDAYS = "misc.mytabledays";
    public static final String MISCMYTABLEMOVEINTERVALDAYS = "misc.mytablemoveintervaldays";
    public static final String MISCMYTABLEINTERVALDAYS = "misc.mytableintervaldays";
    public static final String MISCMYEQUALIZE = "misc.myequalize[@enable]";
    public static final String MISCMYGRAPHEQUALIZE = "misc.mygraphequalize[@enable]";
    public static final String MISCMYGRAPHEQUALIZEUNIFY = "misc.mygraphequalizeunify[@enable]";
    public static final String TESTRECOMMENDFUTUREDAYS = "test.recommend.futuredays";
    public static final String TESTRECOMMENDINTERVALDAYS = "test.recommend.intervaldays";
    @Deprecated
    public static final String TESTRECOMMENDINTERVALTIMES = "test.recommend.intervaltimes";
    public static final String TESTRECOMMENDITERATIONS = "test.recommend.iterations";
    public static final String TESTRECOMMENDPERIOD = "test.recommend.period";
    public static final String TESTRECOMMENDGENERATIONS = "test.recommend.generations";
    public static final String TESTRECOMMENDCHILDREN = "test.recommend.children";
    public static final String TESTRECOMMENDSELECT = "test.recommend.select";
    public static final String TESTRECOMMENDELITE= "test.recommend.elite";
    public static final String TESTRECOMMENDMUTATE = "test.recommend.mutate";
    public static final String TESTRECOMMENDCROSSOVER = "test.recommend.crossover";
    public static final String AGGREGATORS = "aggregators[@enable]";
    public static final String AGGREGATORSMACDRSIRECOMMENDER = "aggregators.macdrsirecommender[@enable]";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAM = "aggregators.macdrsirecommender.weightbuyhistogram";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAMDELTA = "aggregators.macdrsirecommender.weightbuyhistogramdelta";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUM = "aggregators.macdrsirecommender.weightbuymomemtum";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUMDELTA = "aggregators.macdrsirecommender.weightbuymomemtumdelta";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMRSI = "aggregators.macdrsirecommender.weightbuyrsi";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYRSIDELTA = "aggregators.macdrsirecommender.weightbuyrsidelta";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAM = "aggregators.macdrsirecommender.weightsellhistogram";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAMDELTA = "aggregators.macdrsirecommender.weightsellhistogramdelta";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUM = "aggregators.macdrsirecommender.weightsellmomemtum";
    public static final String AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUMDELTA = "aggregators.macdrsirecommender.weightsellmomemtumdelta";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSI = "aggregators.macdrsirecommender.weightsellrsi";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSIDELTA = "aggregators.macdrsirecommender.weightsellrsidelta";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAMNODE = "aggregators.macdrsirecommender.weightbuyhistogramnode";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAMDELTANODE = "aggregators.macdrsirecommender.weightbuyhistogramdeltanode";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUMNODE = "aggregators.macdrsirecommender.weightbuymomemtumnode";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUMDELTANODE = "aggregators.macdrsirecommender.weightbuymomemtumdeltanode";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYRSINODE = "aggregators.macdrsirecommender.weightbuyrsinode";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYRSIDELTANODE = "aggregators.macdrsirecommender.weightbuyrsideltanode";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAMNODE = "aggregators.macdrsirecommender.weightsellhistogramnode";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAMDELTANODE = "aggregators.macdrsirecommender.weightsellhistogramdeltanode";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUMNODE = "aggregators.macdrsirecommender.weightsellmomemtumnode";
    public static final String AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUMDELTANODE = "aggregators.macdrsirecommender.weightsellmomemtumdeltanode";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSINODE = "aggregators.macdrsirecommender.weightsellrsinode";
    public static final String  AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSIDELTANODE = "aggregators.macdrsirecommender.weightsellrsideltanode";
   public static Map<String, Class> map = new HashMap();
    
    public static void makeTypeMap() {
        if (!map.isEmpty()) {
            return;
        }
        map.put(ConfigConstants.DATABASESPARK, Boolean.class);
        map.put(ConfigConstants.DATABASESPARKSPARKMASTER, String.class);
        map.put(ConfigConstants.DATABASEHIBERNATE, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNING, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNINGSPARKML, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNINGSPARMMLSPARKMASTER, String.class);
        map.put(ConfigConstants.MACHINELEARNINGSPARKMLMCP, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNINGSPARKMLLR, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNINGTENSORFLOW, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNINGTENSORFLOWDNN, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNINGTENSORFLOWL, Boolean.class);
        map.put(ConfigConstants.INDICATORS, Boolean.class);
        map.put(ConfigConstants.INDICATORSMOVE, Boolean.class);
        map.put(ConfigConstants.INDICATORSMACD, Boolean.class);
        map.put(ConfigConstants.INDICATORSMACDMACDHISTOGRAMDELTA, Boolean.class);
        map.put(ConfigConstants.INDICATORSMACDMACHHISTOGRAMDELTADAYS, Integer.class);
        
        map.put(ConfigConstants. INDICATORSMACDMACDMOMENTUMDELTA, Boolean.class);
        map.put(ConfigConstants.INDICATORSMACDACDMOMENTUMDELTADAYS, Integer.class);
        map.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTS, Boolean.class);
        map.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSBUYHISTOGRAM, Integer.class);
        map.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSBUYHISTOGRAMDELTA, Integer.class);
        map.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSBUYMOMENTUM, Integer.class);
        map.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSBUGMOMENTUMDELTA, Integer.class);
        map.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSSELLHISTOGRAM, Integer.class);
        map.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSSELLHISTOGRAMDELTA, Integer.class);
        map.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSSELLMOMENTUM, Integer.class);
        map.put(ConfigConstants.INDICATORSMACDRECOMMENDWEIGHTSSELLMOMENTUMDELTA, Integer.class);
        map.put(ConfigConstants.INDICATORSMACDMACHINELEARNING, Boolean.class);
        map.put(ConfigConstants.INDICATORSMACDMACHINELEARNINGMOMENTUMML, Boolean.class);
        map.put(ConfigConstants.INDICATORSMACDMACHINELEARNINGHISTOGRAMML, Boolean.class);
        map.put(ConfigConstants. INDICATORSMACDDAYSBEFOREZERO , Integer.class);
        map.put(ConfigConstants. INDICATORSMACDDAYSAFTERZERO, Integer.class);
        map.put(ConfigConstants. INDICATORSRSI, Boolean.class);
        map.put(ConfigConstants. INDICATORSRSIDELTA, Boolean.class);
        map.put(ConfigConstants. INDICATORSRSIDELTADAYS, Integer.class);
        map.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTS, Boolean.class);
        map.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTSBUY, Integer.class);
        map.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTSBUYDELTA, Integer.class);
        map.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTSSELL, Integer.class);
        map.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTSSELLDELTA, Integer.class);
        map.put(ConfigConstants. INDICATORSSTOCHRSI, Boolean.class);
        map.put(ConfigConstants. INDICATORSSTOCHRSIDELTA, Boolean.class);
        map.put(ConfigConstants. INDICATORSSTOCHRSIDELTADAYS, Integer.class);
        map.put(ConfigConstants. INDICATORSCCI, Boolean.class);
        map.put(ConfigConstants. INDICATORSCCIDELTA , Boolean.class);
        map.put(ConfigConstants.INDICATORSCCIDELTADAYS, Integer.class);
        map.put(ConfigConstants.INDICATORSATR , Boolean.class);
        map.put(ConfigConstants.INDICATORSATRDELTA, Boolean.class);
        map.put(ConfigConstants.INDICATORSATRDELTADAYS, Integer.class);
        map.put(ConfigConstants.INDICATORSSTOCH, Boolean.class);
        map.put(ConfigConstants.INDICATORSSTOCHSTOCHDELTA , Boolean.class);
        map.put(ConfigConstants.INDICATORSSTOCHSTOCHDELTADAYS, Integer.class);
        map.put(ConfigConstants.PREDICTORS, Boolean.class);
        map.put(ConfigConstants.PREDICTORSLSTM, Boolean.class);
        map.put(ConfigConstants.PREDICTORSLSTMEPOCHS, Integer.class);
        map.put(ConfigConstants.PREDICTORSLSTMHORIZON, Integer.class);
        map.put(ConfigConstants.PREDICTORSLSTMWINDOWSIZE, Integer.class);
        map.put(ConfigConstants.MISC, Boolean.class);
        map.put(ConfigConstants.MISCPERCENTIZEPRICEINDEX, Boolean.class);
        map.put(ConfigConstants.MISCMLSTATS, Boolean.class);
        map.put(ConfigConstants.MISCOTHERSTATS, Boolean.class);
        map.put(ConfigConstants.MISCMYDAYS, Integer.class);
        map.put(ConfigConstants.MISCMYTOPBOTTOM, Integer.class);
        map.put(ConfigConstants.MISCMYTBLEDAYS, Integer.class);
        map.put(ConfigConstants.MISCMYTABLEMOVEINTERVALDAYS, Integer.class);
        map.put(ConfigConstants.MISCMYTABLEINTERVALDAYS, Integer.class);
        map.put(ConfigConstants.MISCMYEQUALIZE, Boolean.class);
        map.put(ConfigConstants.MISCMYGRAPHEQUALIZE, Boolean.class);
        map.put(ConfigConstants.MISCMYGRAPHEQUALIZEUNIFY, Boolean.class);
        map.put(ConfigConstants.TESTRECOMMENDFUTUREDAYS, Integer.class);
        map.put(ConfigConstants.TESTRECOMMENDINTERVALDAYS, Integer.class);
        map.put(ConfigConstants.TESTRECOMMENDINTERVALTIMES, Integer.class);
        map.put(ConfigConstants.TESTRECOMMENDITERATIONS, Integer.class);
        map.put(ConfigConstants.TESTRECOMMENDPERIOD, String.class);
        map.put(ConfigConstants.TESTRECOMMENDGENERATIONS, Integer.class);
        map.put(ConfigConstants.TESTRECOMMENDCHILDREN, Integer.class);
        map.put(ConfigConstants.TESTRECOMMENDCROSSOVER, Integer.class);
        map.put(ConfigConstants.TESTRECOMMENDELITE, Integer.class);
        map.put(ConfigConstants.TESTRECOMMENDMUTATE, Integer.class);
        map.put(ConfigConstants.TESTRECOMMENDSELECT, Integer.class);
        map.put(ConfigConstants.AGGREGATORS, Boolean.class);
       map.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDER, Boolean.class);
       map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAM , Integer.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAMDELTA , Integer.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUM , Integer.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUMDELTA , Integer.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMRSI, Integer.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYRSIDELTA , Integer.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAM , Integer.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAMDELTA, Integer.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUM , Integer.class);
        map.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUMDELTA, Integer.class);
        map.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSI, Integer.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSIDELTA, Integer.class);
       map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAMNODE , String.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAMDELTANODE , String.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUMNODE , String.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUMDELTANODE , String.class);
        map.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYRSINODE, String.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYRSIDELTANODE , String.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAMNODE , String.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAMDELTANODE , String.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUMNODE , String.class);
        map.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUMDELTANODE, String.class);
        map.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSINODE, String.class);
        map.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSIDELTANODE, String.class);
    }

    public static Map<String, Object> deflt = new HashMap();
    public static void makeDefaultMap() {
        if (!deflt.isEmpty()) {
            return;
        }
        deflt.put(ConfigConstants.DATABASESPARK, Boolean.TRUE);
        deflt.put(ConfigConstants.DATABASESPARKSPARKMASTER, "spark://127.0.0.1:7077");
        deflt.put(ConfigConstants.DATABASEHIBERNATE, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNING, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNINGSPARKML, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNINGSPARMMLSPARKMASTER, "spark://127.0.0.1:7077");
        deflt.put(ConfigConstants.MACHINELEARNINGSPARKMLMCP, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNINGSPARKMLLR, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNINGTENSORFLOW, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNINGTENSORFLOWDNN, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNINGTENSORFLOWL, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORS, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMOVE, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMACD, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMACDMACDHISTOGRAMDELTA, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMACDMACHHISTOGRAMDELTADAYS, 3);
        
        deflt.put(ConfigConstants. INDICATORSMACDMACDMOMENTUMDELTA, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMACDACDMOMENTUMDELTADAYS, 3);
        deflt.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTS, Boolean.TRUE);
        deflt.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSBUYHISTOGRAM, 40);
        deflt.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSBUYHISTOGRAMDELTA, 20);
        deflt.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSBUYMOMENTUM, 20);
        deflt.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSBUGMOMENTUMDELTA, 20);
        deflt.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSSELLHISTOGRAM, 40);
        deflt.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSSELLHISTOGRAMDELTA, 20);
        deflt.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSSELLMOMENTUM, 20);
        deflt.put(ConfigConstants.INDICATORSMACDRECOMMENDWEIGHTSSELLMOMENTUMDELTA, 20);
        deflt.put(ConfigConstants.INDICATORSMACDMACHINELEARNING, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMACDMACHINELEARNINGMOMENTUMML, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMACDMACHINELEARNINGHISTOGRAMML, Boolean.TRUE);
        deflt.put(ConfigConstants. INDICATORSMACDDAYSBEFOREZERO , 25);
        deflt.put(ConfigConstants. INDICATORSMACDDAYSAFTERZERO, 10);
        deflt.put(ConfigConstants. INDICATORSRSI, Boolean.TRUE);
        deflt.put(ConfigConstants. INDICATORSRSIDELTA, Boolean.TRUE);
        deflt.put(ConfigConstants. INDICATORSRSIDELTADAYS, 3);
        deflt.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTS, Boolean.TRUE);
        deflt.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTSBUY, 50);
        deflt.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTSBUYDELTA, 50);
        deflt.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTSSELL, 50);
        deflt.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTSSELLDELTA, 50);
        deflt.put(ConfigConstants. INDICATORSSTOCHRSI, Boolean.TRUE);
        deflt.put(ConfigConstants. INDICATORSSTOCHRSIDELTA, Boolean.TRUE);
        deflt.put(ConfigConstants. INDICATORSSTOCHRSIDELTADAYS, 3);
        deflt.put(ConfigConstants. INDICATORSCCI, Boolean.TRUE);
        deflt.put(ConfigConstants. INDICATORSCCIDELTA , Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSCCIDELTADAYS, 3);
        deflt.put(ConfigConstants.INDICATORSATR , Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSATRDELTA, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSATRDELTADAYS, 3);
        deflt.put(ConfigConstants.INDICATORSSTOCH, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSSTOCHSTOCHDELTA , Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSSTOCHSTOCHDELTADAYS, 3);
        deflt.put(ConfigConstants.PREDICTORS, Boolean.TRUE);
        deflt.put(ConfigConstants.PREDICTORSLSTM, Boolean.TRUE);
        deflt.put(ConfigConstants.PREDICTORSLSTMEPOCHS, 5);
        deflt.put(ConfigConstants.PREDICTORSLSTMHORIZON, 5);
        deflt.put(ConfigConstants.PREDICTORSLSTMWINDOWSIZE, 3);
        deflt.put(ConfigConstants.MISC, Boolean.TRUE);
        deflt.put(ConfigConstants.MISCPERCENTIZEPRICEINDEX, Boolean.TRUE);
        deflt.put(ConfigConstants.MISCMLSTATS, Boolean.TRUE);
        deflt.put(ConfigConstants.MISCOTHERSTATS, Boolean.TRUE);
        deflt.put(ConfigConstants.MISCMYDAYS, Integer.class);
        deflt.put(ConfigConstants.MISCMYTOPBOTTOM, 10);
        deflt.put(ConfigConstants.MISCMYTBLEDAYS, 180);
        deflt.put(ConfigConstants.MISCMYTABLEMOVEINTERVALDAYS, 5);
        deflt.put(ConfigConstants.MISCMYTABLEINTERVALDAYS, 1);
        deflt.put(ConfigConstants.MISCMYEQUALIZE, Boolean.TRUE);
        deflt.put(ConfigConstants.MISCMYGRAPHEQUALIZE, Boolean.TRUE);
        deflt.put(ConfigConstants.MISCMYGRAPHEQUALIZEUNIFY, Boolean.TRUE);
        deflt.put(ConfigConstants.TESTRECOMMENDFUTUREDAYS, 10);
        deflt.put(ConfigConstants.TESTRECOMMENDINTERVALDAYS, 5);
        deflt.put(ConfigConstants.TESTRECOMMENDINTERVALTIMES, 10);
        deflt.put(ConfigConstants.TESTRECOMMENDITERATIONS, 100);
        deflt.put(ConfigConstants.TESTRECOMMENDPERIOD, "Price");
        deflt.put(ConfigConstants.TESTRECOMMENDGENERATIONS, 2);
        deflt.put(ConfigConstants.TESTRECOMMENDCHILDREN, 4);
        deflt.put(ConfigConstants.TESTRECOMMENDELITE, 1);
        deflt.put(ConfigConstants.TESTRECOMMENDMUTATE, 1);
        deflt.put(ConfigConstants.TESTRECOMMENDCROSSOVER, 1);
        deflt.put(ConfigConstants.TESTRECOMMENDSELECT, 16);
        deflt.put(ConfigConstants.AGGREGATORS, Boolean.TRUE);
       deflt.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDER, Boolean.TRUE);
       deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAM , 40);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAMDELTA , 20);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUM , 20);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUMDELTA , 20);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMRSI, 20);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYRSIDELTA , 20);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAM , 40);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAMDELTA, 20);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUM , 20);
        deflt.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUMDELTA, 20);
        deflt.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSI, 20);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSIDELTA, 20);
       deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAMNODE , json);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAMDELTANODE , json);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUMNODE , json);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUMDELTANODE , json);
        deflt.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYRSINODE, json);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYRSIDELTANODE , json);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAMNODE , json);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAMDELTANODE, json);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUMNODE , json);
        deflt.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUMDELTANODE, json);
        deflt.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSINODE, json);
        deflt.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSIDELTANODE, json);
    }

    private final static String json = "{\"_class\": \"roart.calculate.CalcMACDNode\", \"className\":null,\"minMutateThresholdRange\":-5.0,\"maxMutateThresholdRange\":5.0,\"threshold\":-2.476814906438654,\"useminmaxthreshold\":true,\"usethreshold\":false,\"divideminmaxthreshold\":true,\"weight\":31.0,\"changeSignWhole\":false,\"doBuy\":false}";
    
    public static Map<String, String> text = new HashMap();
    
    public static void makeTextMap() {
        if (!text.isEmpty()) {
            return;
        }
        text.put(ConfigConstants.DATABASESPARK, "Enable Spark Database backend");
        text.put(ConfigConstants.DATABASESPARKSPARKMASTER, "Database Spark Master");
        text.put(ConfigConstants.DATABASEHIBERNATE, "Enable Hibernate Database backend");
        text.put(ConfigConstants.MACHINELEARNING, "Enable machine learning");
        text.put(ConfigConstants.MACHINELEARNINGSPARKML, "Enable Spark ML");
        text.put(ConfigConstants.MACHINELEARNINGSPARMMLSPARKMASTER, "Machine Learning Spark Master");
        text.put(ConfigConstants.MACHINELEARNINGSPARKMLMCP, "Enable Spark ML MCP");
        text.put(ConfigConstants.MACHINELEARNINGSPARKMLLR, "Enable Spark ML LR");
        text.put(ConfigConstants.MACHINELEARNINGTENSORFLOW, "Enable Tensorflow");
        text.put(ConfigConstants.MACHINELEARNINGTENSORFLOWDNN, "Enable Tensorflow DNN");
        text.put(ConfigConstants.MACHINELEARNINGTENSORFLOWL, "Enable Tensorflow L");
        text.put(ConfigConstants.INDICATORS, "Enable indicators");
        text.put(ConfigConstants.INDICATORSMOVE, "Enable move indicator");
        text.put(ConfigConstants.INDICATORSMACD, "Enable MACD indicator");
        text.put(ConfigConstants.INDICATORSMACDMACDHISTOGRAMDELTA, "Enable MACD histogram delta");
        text.put(ConfigConstants.INDICATORSMACDMACHHISTOGRAMDELTADAYS, "MACD histogram delta days");
        
        text.put(ConfigConstants. INDICATORSMACDMACDMOMENTUMDELTA, "Enable MACD momentum delta");
        text.put(ConfigConstants.INDICATORSMACDACDMOMENTUMDELTADAYS, "MACD momentum delta days");
        text.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTS, "Enable MACD buy/sell recommendation");
        text.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSBUYHISTOGRAM, "Buy weight histogram");
        text.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSBUYHISTOGRAMDELTA, "Buy weight histogram delta");
        text.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSBUYMOMENTUM, "Buy weight momentum");
        text.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSBUGMOMENTUMDELTA, "Buy weight momentum delta");
        text.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSSELLHISTOGRAM, "Sell weight histogram");
        text.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSSELLHISTOGRAMDELTA, "Sell weight histogram delta");
        text.put(ConfigConstants. INDICATORSMACDRECOMMENDWEIGHTSSELLMOMENTUM, "Sell weight momentum");
        text.put(ConfigConstants.INDICATORSMACDRECOMMENDWEIGHTSSELLMOMENTUMDELTA, "Sell weight momentum delta");
        text.put(ConfigConstants.INDICATORSMACDMACHINELEARNING, "Enable indicator MACD machine learning");
        text.put(ConfigConstants.INDICATORSMACDMACHINELEARNINGMOMENTUMML, "Enable indicator MACD momentum machine learning");
        text.put(ConfigConstants.INDICATORSMACDMACHINELEARNINGHISTOGRAMML, "Enable indicator MACD histogram machine learning");
        text.put(ConfigConstants. INDICATORSMACDDAYSBEFOREZERO , "Days before zero");
        text.put(ConfigConstants. INDICATORSMACDDAYSAFTERZERO, "Days after zero");
        text.put(ConfigConstants. INDICATORSRSI, "Enable indicator RSI");
        text.put(ConfigConstants. INDICATORSRSIDELTA, "Enable indicator RSI delta");
        text.put(ConfigConstants. INDICATORSRSIDELTADAYS, "RSI delta days");
        text.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTS, "Enable buy/sell indicator RSI");
        text.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTSBUY, "RSI buy weight");
        text.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTSBUYDELTA, "RSI delta buy weight");
        text.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTSSELL, "RSI sell weight");
        text.put(ConfigConstants. INDICATORSRSIRECOMMENDWEIGHTSSELLDELTA, "RSI delta sell weight");
       text.put(ConfigConstants. INDICATORSSTOCHRSI, "Enable indicator STOCH RSI");
        text.put(ConfigConstants. INDICATORSSTOCHRSIDELTA, "Enable indicator STOCH RSI delta");
        text.put(ConfigConstants. INDICATORSSTOCHRSIDELTADAYS, "STOCH RSI delta days");
        text.put(ConfigConstants. INDICATORSCCI, "Enable indicator CCI");
        text.put(ConfigConstants. INDICATORSCCIDELTA , "Enable indicator CCI delta");
        text.put(ConfigConstants.INDICATORSCCIDELTADAYS, "CCI delta days");
        text.put(ConfigConstants.INDICATORSATR , "Enable indicator ATR");
        text.put(ConfigConstants.INDICATORSATRDELTA, "Enable indicator ATR delta");
        text.put(ConfigConstants.INDICATORSATRDELTADAYS, "ATR delta days");
        text.put(ConfigConstants.INDICATORSSTOCH, "Enable indicator STOCH");
        text.put(ConfigConstants.INDICATORSSTOCHSTOCHDELTA , "Enable indicator STOCH delta");
        text.put(ConfigConstants.INDICATORSSTOCHSTOCHDELTADAYS, "STOCH delta days");
        text.put(ConfigConstants.PREDICTORS, "Enable predictors");
        text.put(ConfigConstants.PREDICTORSLSTM, "Enable LSTM predictor");
        text.put(ConfigConstants.PREDICTORSLSTMEPOCHS, "LSTM epochs");
        text.put(ConfigConstants.PREDICTORSLSTMHORIZON, "LSTM horizon");
        text.put(ConfigConstants.PREDICTORSLSTMWINDOWSIZE, "LSTM windowsize");
        text.put(ConfigConstants.MISC, "Misc");
        text.put(ConfigConstants.MISCPERCENTIZEPRICEINDEX, "Enable turning price/index into percent based on first date");
        text.put(ConfigConstants.MISCMLSTATS, "Enable ML stats for time usage");
        text.put(ConfigConstants.MISCOTHERSTATS, "Enable other stat pages");
        text.put(ConfigConstants.MISCMYDAYS, "Number of days to display");
        text.put(ConfigConstants.MISCMYTOPBOTTOM, "Number of items to display");
        text.put(ConfigConstants.MISCMYTBLEDAYS, "Table days");
        text.put(ConfigConstants.MISCMYTABLEMOVEINTERVALDAYS, "Interval days for table move");
        text.put(ConfigConstants.MISCMYTABLEINTERVALDAYS, "Table interval days");
        text.put(ConfigConstants.MISCMYEQUALIZE, "Enable equalizing");
        text.put(ConfigConstants.MISCMYGRAPHEQUALIZE, "Enable graph equalizing");
        text.put(ConfigConstants.MISCMYGRAPHEQUALIZEUNIFY, "Enable unified graph equalizing");
        text.put(ConfigConstants.TESTRECOMMENDFUTUREDAYS, "Test recommender future days");
        text.put(ConfigConstants.TESTRECOMMENDINTERVALDAYS, "Test recommender interval days");
        text.put(ConfigConstants.TESTRECOMMENDINTERVALTIMES, "Deprecated Test recommender interval times");
        text.put(ConfigConstants.TESTRECOMMENDITERATIONS, "Test recommender iterations");
        text.put(ConfigConstants.TESTRECOMMENDPERIOD, "Test recommender period");
        text.put(ConfigConstants.TESTRECOMMENDGENERATIONS, "Test recommender generations");
        text.put(ConfigConstants.TESTRECOMMENDCHILDREN, "Test recommender children");
        text.put(ConfigConstants.TESTRECOMMENDCROSSOVER, "Test recommender crossover");
        text.put(ConfigConstants.TESTRECOMMENDELITE, "Test recommender elite");
        text.put(ConfigConstants.TESTRECOMMENDSELECT, "Test recommender select");
        text.put(ConfigConstants.TESTRECOMMENDMUTATE, "Test recommender mutate");
        text.put(ConfigConstants.AGGREGATORS, "Enable aggregators");
       text.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDER, "Enable aggregated MACD RSI recommender");
       text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAM , "Buy weight histogram");
       text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAMDELTA , "Buy weight histogram delta");
       text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUM , "Buy weight momentum");
       text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUMDELTA ,"Buy weight momentum delta");
       text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMRSI, "Buy weight RSI");
		text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYRSIDELTA , "Buy weight RSI delta");
		text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAM ,"Sell weight histogram");
		text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAMDELTA, "Sell weight histogram delta");
		text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUM ,"Sell weight momentum");
		text.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUMDELTA,"Sell weight momentum delta");
		text.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSI, "Sell weight RSI");
		text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSIDELTA, "Sell weight RSI delta");
       text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAMNODE , "Buy weight histogram node");
       text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYHISTOGRAMDELTANODE , "Buy weight histogram delta node");
       text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUMNODE , "Buy weight momentum node");
       text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYMOMENTUMDELTANODE ,"Buy weight momentum delta node");
       text.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYRSINODE, "Buy weight RSI node");
		text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSBUYRSIDELTANODE , "Buy weight RSI delta node");
		text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAMNODE ,"Sell weight histogram node");
		text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLHISTOGRAMDELTANODE, "Sell weight histogram delta node");
		text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUMNODE ,"Sell weight momentum node");
		text.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLMOMENTUMDELTANODE,"Sell weight momentum delta node");
		text.put(ConfigConstants.AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSINODE, "Sell weight RSI node");
		text.put(ConfigConstants. AGGREGATORSMACDRSIRECOMMENDWEIGHTSSELLRSIDELTANODE, "Sell weight RSI delta node");
       
    }


}
