package roart.config;

import java.util.HashMap;
import java.util.Map;
import roart.calculate.CalcComplexNode;
import roart.category.CategoryConstants;
import roart.config.ConfigConstants;

public class ConfigConstantMaps {
    public static Map<String, Class> map = new HashMap();

    public static void makeTypeMap() {
        if (!map.isEmpty()) {
            return;
        }
        map.put(ConfigConstants.DATABASEMAXHOLES, Integer.class);
        map.put(ConfigConstants.DATABASESPARK, Boolean.class);
        map.put(ConfigConstants.DATABASESPARKSPARKMASTER, String.class);
        map.put(ConfigConstants.DATABASEHIBERNATE, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNING, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNINGMP, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNINGMPCPUFRACTION, Integer.class);
        map.put(ConfigConstants.MACHINELEARNINGSPARKML, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNINGSPARMMLSPARKMASTER, String.class);
        map.put(ConfigConstants.MACHINELEARNINGSPARKMLMCP, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNINGSPARKMLLR, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNINGTENSORFLOW, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNINGTENSORFLOWDNN, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNINGTENSORFLOWL, Boolean.class);
        map.put(ConfigConstants.MACHINELEARNINGTENSORFLOWSERVER, String.class);
        map.put(ConfigConstants.INDICATORS, Boolean.class);
        map.put(ConfigConstants.INDICATORSMOVE, Boolean.class);
        map.put(ConfigConstants.INDICATORSMACD, Boolean.class);
        map.put(ConfigConstants.INDICATORSMACDMACDHISTOGRAMDELTA, Boolean.class);
        map.put(ConfigConstants.INDICATORSMACDMACHHISTOGRAMDELTADAYS, Integer.class);

        map.put(ConfigConstants.INDICATORSMACDMACDMOMENTUMDELTA, Boolean.class);
        map.put(ConfigConstants.INDICATORSMACDACDMOMENTUMDELTADAYS, Integer.class);
        map.put(ConfigConstants.INDICATORSMACDRECOMMEND, Boolean.class);
        map.put(ConfigConstants.INDICATORSMACDRECOMMENDBUY, String.class);
        map.put(ConfigConstants.INDICATORSMACDRECOMMENDBUYWEIGHTHISTOGRAM, Integer.class);
        map.put(ConfigConstants.INDICATORSMACDRECOMMENDBUYWEIGHTHISTOGRAMDELTA, Integer.class);
        map.put(ConfigConstants.INDICATORSMACDRECOMMENDBUYWEIGHTMOMENTUM, Integer.class);
        map.put(ConfigConstants.INDICATORSMACDRECOMMENDBUYWEIGHTMOMENTUMDELTA, Integer.class);
        map.put(ConfigConstants.INDICATORSMACDRECOMMENDSELL, String.class);
        map.put(ConfigConstants.INDICATORSMACDRECOMMENDSELLWEIGHTHISTOGRAM, Integer.class);
        map.put(ConfigConstants.INDICATORSMACDRECOMMENDSELLWEIGHTHISTOGRAMDELTA, Integer.class);
        map.put(ConfigConstants.INDICATORSMACDRECOMMENDSELLWEIGHTMOMENTUM, Integer.class);
        map.put(ConfigConstants.INDICATORSMACDRECOMMENDSELLWEIGHTMOMENTUMDELTA, Integer.class);
        map.put(ConfigConstants.INDICATORSMACDMACHINELEARNING, Boolean.class);
        map.put(ConfigConstants.INDICATORSMACDMACHINELEARNINGMOMENTUMML, Boolean.class);
        map.put(ConfigConstants.INDICATORSMACDMACHINELEARNINGHISTOGRAMML, Boolean.class);
        map.put(ConfigConstants.INDICATORSMACDDAYSBEFOREZERO, Integer.class);
        map.put(ConfigConstants.INDICATORSMACDDAYSAFTERZERO, Integer.class);
        map.put(ConfigConstants.INDICATORSRSI, Boolean.class);
        map.put(ConfigConstants.INDICATORSRSIDELTA, Boolean.class);
        map.put(ConfigConstants.INDICATORSRSIDELTADAYS, Integer.class);
        map.put(ConfigConstants.INDICATORSRSIRECOMMEND, Boolean.class);
        map.put(ConfigConstants.INDICATORSRSIRECOMMENDBUY, String.class);
        map.put(ConfigConstants.INDICATORSRSIRECOMMENDBUYWEIGHT, Integer.class);
        map.put(ConfigConstants.INDICATORSRSIRECOMMENDBUYWEIGHTDELTA, Integer.class);
        map.put(ConfigConstants.INDICATORSRSIRECOMMENDSELL, String.class);
        map.put(ConfigConstants.INDICATORSRSIRECOMMENDSELLWEIGHT, Integer.class);
        map.put(ConfigConstants.INDICATORSRSIRECOMMENDSELLWEIGHTDELTA, Integer.class);
        map.put(ConfigConstants.INDICATORSSTOCHRSI, Boolean.class);
        map.put(ConfigConstants.INDICATORSSTOCHRSIDELTA, Boolean.class);
        map.put(ConfigConstants.INDICATORSSTOCHRSIDELTADAYS, Integer.class);
        map.put(ConfigConstants.INDICATORSCCI, Boolean.class);
        map.put(ConfigConstants.INDICATORSCCIDELTA, Boolean.class);
        map.put(ConfigConstants.INDICATORSCCIDELTADAYS, Integer.class);
        map.put(ConfigConstants.INDICATORSATR, Boolean.class);
        map.put(ConfigConstants.INDICATORSATRDELTA, Boolean.class);
        map.put(ConfigConstants.INDICATORSATRDELTADAYS, Integer.class);
        map.put(ConfigConstants.INDICATORSSTOCH, Boolean.class);
        map.put(ConfigConstants.INDICATORSSTOCHSTOCHDELTA, Boolean.class);
        map.put(ConfigConstants.INDICATORSSTOCHSTOCHDELTADAYS, Integer.class);
        map.put(ConfigConstants.PREDICTORS, Boolean.class);
        map.put(ConfigConstants.PREDICTORSLSTM, Boolean.class);
        map.put(ConfigConstants.PREDICTORSLSTMEPOCHS, Integer.class);
        map.put(ConfigConstants.PREDICTORSLSTMHORIZON, Integer.class);
        map.put(ConfigConstants.PREDICTORSLSTMWINDOWSIZE, Integer.class);
        map.put(ConfigConstants.MISC, Boolean.class);
        map.put(ConfigConstants.MISCPERCENTIZEPRICEINDEX, Boolean.class);
        map.put(ConfigConstants.MISCMLSTATS, Boolean.class);
        map.put(ConfigConstants.MISCOTHERSTATS, Boolean.class);
        map.put(ConfigConstants.MISCMYDAYS, Integer.class);
        map.put(ConfigConstants.MISCMYTOPBOTTOM, Integer.class);
        map.put(ConfigConstants.MISCMYTBLEDAYS, Integer.class);
        map.put(ConfigConstants.MISCMYTABLEMOVEINTERVALDAYS, Integer.class);
        map.put(ConfigConstants.MISCMYTABLEINTERVALDAYS, Integer.class);
        map.put(ConfigConstants.MISCMYEQUALIZE, Boolean.class);
        map.put(ConfigConstants.MISCMYGRAPHEQUALIZE, Boolean.class);
        map.put(ConfigConstants.MISCMYGRAPHEQUALIZEUNIFY, Boolean.class);
        map.put(ConfigConstants.TESTINDICATORRECOMMENDERSIMPLEFUTUREDAYS, Integer.class);
        map.put(ConfigConstants.TESTINDICATORRECOMMENDERSIMPLEINTERVALDAYS, Integer.class);
        map.put(ConfigConstants.TESTINDICATORRECOMMENDERCOMPLEXFUTUREDAYS, Integer.class);
        map.put(ConfigConstants.TESTINDICATORRECOMMENDERCOMPLEXINTERVALDAYS, Integer.class);
        map.put(ConfigConstants.TESTRECOMMENDINTERVALTIMES, Integer.class);
        map.put(ConfigConstants.TESTRECOMMENDITERATIONS, Integer.class);
        map.put(ConfigConstants.TESTRECOMMENDPERIOD, String.class);
        map.put(ConfigConstants.TESTRECOMMENDFACTOR, Integer.class);
        map.put(ConfigConstants.EVOLUTION, String.class);
        //map.put(ConfigConstants.EVOLUTION, Boolean.class);
        map.put(ConfigConstants.EVOLUTIONGENERATIONS, Integer.class);
        map.put(ConfigConstants.EVOLUTIONCHILDREN, Integer.class);
        map.put(ConfigConstants.EVOLUTIONCROSSOVER, Integer.class);
        map.put(ConfigConstants.EVOLUTIONGENERATIONCREATE, Integer.class);
        map.put(ConfigConstants.EVOLUTIONELITE, Integer.class);
        map.put(ConfigConstants.EVOLUTIONELITECLONEANDMUTATE, Integer.class);
        map.put(ConfigConstants.EVOLUTIONMUTATE, Integer.class);
        map.put(ConfigConstants.EVOLUTIONSELECT, Integer.class);
        map.put(ConfigConstants.AGGREGATORS, Boolean.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDER, Boolean.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLE, Boolean.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACD, Boolean.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUY, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUYWEIGHTHISTOGRAM, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUYWEIGHTHISTOGRAMDELTA, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUYWEIGHTMOMENTUM, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUYWEIGHTMOMENTUMDELTA, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELL, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELLWEIGHTHISTOGRAM, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELLWEIGHTHISTOGRAMDELTA, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELLWEIGHTMOMENTUM, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELLWEIGHTMOMENTUMDELTA, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSI, Boolean.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSIBUY, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSIBUYWEIGHTRSI, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSIBUYWEIGHTRSIDELTA, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSISELL, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSISELLWEIGHTRSI, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSISELLWEIGHTRSIDELTA, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACD, Boolean.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUY, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUYWEIGHTHISTOGRAMNODE, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUYWEIGHTHISTOGRAMDELTANODE, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUYWEIGHTMOMENTUMNODE, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUYWEIGHTMOMENTUMDELTANODE, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELL, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELLWEIGHTHISTOGRAMNODE, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELLWEIGHTHISTOGRAMDELTANODE, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELLWEIGHTMOMENTUMNODE, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELLWEIGHTMOMENTUMDELTANODE, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEX, Boolean.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSI, Boolean.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSIBUY, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSIBUYWEIGHTRSINODE, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSIBUYWEIGHTRSIDELTANODE, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSISELL, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSISELLWEIGHTRSINODE, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSISELLWEIGHTRSIDELTANODE, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATOR, Boolean.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORMACD, Boolean.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORRSI, Boolean.class);
        map.put(ConfigConstants.AGGREGATORSINDICATOREXTRAS, String.class);
        map.put(ConfigConstants.AGGREGATORSINDICATOREXTRASDELTAS, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATOREXTRASMACD, Boolean.class);
        map.put(ConfigConstants.AGGREGATORSINDICATOREXTRASRSI, Boolean.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORFUTUREDAYS, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORINTERVALDAYS, Integer.class);
        map.put(ConfigConstants.AGGREGATORSINDICATORTHRESHOLD, Double.class);
        map.put(ConfigConstants.AGGREGATORSMLMACD, Boolean.class);
    }

    public static Map<String, Object> deflt = new HashMap();
    public static void makeDefaultMap() {
        if (!deflt.isEmpty()) {
            return;
        }
        deflt.put(ConfigConstants.DATABASEMAXHOLES, 5);
        deflt.put(ConfigConstants.DATABASESPARK, Boolean.TRUE);
        deflt.put(ConfigConstants.DATABASESPARKSPARKMASTER, "spark://127.0.0.1:7077");
        deflt.put(ConfigConstants.DATABASEHIBERNATE, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNING, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNINGMP, Boolean.FALSE);
        deflt.put(ConfigConstants.MACHINELEARNINGMPCPUFRACTION, 4);
        deflt.put(ConfigConstants.MACHINELEARNINGSPARKML, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNINGSPARMMLSPARKMASTER, "spark://127.0.0.1:7077");
        deflt.put(ConfigConstants.MACHINELEARNINGSPARKMLMCP, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNINGSPARKMLLR, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNINGTENSORFLOW, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNINGTENSORFLOWDNN, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNINGTENSORFLOWL, Boolean.TRUE);
        deflt.put(ConfigConstants.MACHINELEARNINGTENSORFLOWSERVER, "http://localhost:8000");
        deflt.put(ConfigConstants.INDICATORS, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMOVE, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMACD, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMACDMACDHISTOGRAMDELTA, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMACDMACHHISTOGRAMDELTADAYS, 3);

        deflt.put(ConfigConstants.INDICATORSMACDMACDMOMENTUMDELTA, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMACDACDMOMENTUMDELTADAYS, 3);
        deflt.put(ConfigConstants.INDICATORSMACDRECOMMEND, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMACDRECOMMENDBUY, null);
        deflt.put(ConfigConstants.INDICATORSMACDRECOMMENDBUYWEIGHTHISTOGRAM, 40);
        deflt.put(ConfigConstants.INDICATORSMACDRECOMMENDBUYWEIGHTHISTOGRAMDELTA, 20);
        deflt.put(ConfigConstants.INDICATORSMACDRECOMMENDBUYWEIGHTMOMENTUM, 20);
        deflt.put(ConfigConstants.INDICATORSMACDRECOMMENDBUYWEIGHTMOMENTUMDELTA, 20);
        deflt.put(ConfigConstants.INDICATORSMACDRECOMMENDSELL, null);
        deflt.put(ConfigConstants.INDICATORSMACDRECOMMENDSELLWEIGHTHISTOGRAM, 40);
        deflt.put(ConfigConstants.INDICATORSMACDRECOMMENDSELLWEIGHTHISTOGRAMDELTA, 20);
        deflt.put(ConfigConstants.INDICATORSMACDRECOMMENDSELLWEIGHTMOMENTUM, 20);
        deflt.put(ConfigConstants.INDICATORSMACDRECOMMENDSELLWEIGHTMOMENTUMDELTA, 20);
        deflt.put(ConfigConstants.INDICATORSMACDMACHINELEARNING, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMACDMACHINELEARNINGMOMENTUMML, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMACDMACHINELEARNINGHISTOGRAMML, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSMACDDAYSBEFOREZERO, 25);
        deflt.put(ConfigConstants.INDICATORSMACDDAYSAFTERZERO, 10);
        deflt.put(ConfigConstants.INDICATORSRSI, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSRSIDELTA, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSRSIDELTADAYS, 3);
        deflt.put(ConfigConstants.INDICATORSRSIRECOMMEND, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSRSIRECOMMENDBUY, null);
        deflt.put(ConfigConstants.INDICATORSRSIRECOMMENDBUYWEIGHT, 50);
        deflt.put(ConfigConstants.INDICATORSRSIRECOMMENDBUYWEIGHTDELTA, 50);
        deflt.put(ConfigConstants.INDICATORSRSIRECOMMENDSELL, null);
        deflt.put(ConfigConstants.INDICATORSRSIRECOMMENDSELLWEIGHT, 50);
        deflt.put(ConfigConstants.INDICATORSRSIRECOMMENDSELLWEIGHTDELTA, 50);
        deflt.put(ConfigConstants.INDICATORSSTOCHRSI, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSSTOCHRSIDELTA, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSSTOCHRSIDELTADAYS, 3);
        deflt.put(ConfigConstants.INDICATORSCCI, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSCCIDELTA, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSCCIDELTADAYS, 3);
        deflt.put(ConfigConstants.INDICATORSATR, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSATRDELTA, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSATRDELTADAYS, 3);
        deflt.put(ConfigConstants.INDICATORSSTOCH, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSSTOCHSTOCHDELTA, Boolean.TRUE);
        deflt.put(ConfigConstants.INDICATORSSTOCHSTOCHDELTADAYS, 3);
        deflt.put(ConfigConstants.PREDICTORS, Boolean.TRUE);
        deflt.put(ConfigConstants.PREDICTORSLSTM, Boolean.TRUE);
        deflt.put(ConfigConstants.PREDICTORSLSTMEPOCHS, 5);
        deflt.put(ConfigConstants.PREDICTORSLSTMHORIZON, 5);
        deflt.put(ConfigConstants.PREDICTORSLSTMWINDOWSIZE, 3);
        deflt.put(ConfigConstants.MISC, Boolean.TRUE);
        deflt.put(ConfigConstants.MISCPERCENTIZEPRICEINDEX, Boolean.TRUE);
        deflt.put(ConfigConstants.MISCMLSTATS, Boolean.TRUE);
        deflt.put(ConfigConstants.MISCOTHERSTATS, Boolean.TRUE);
        deflt.put(ConfigConstants.MISCMYDAYS, 180);
        deflt.put(ConfigConstants.MISCMYTOPBOTTOM, 10);
        deflt.put(ConfigConstants.MISCMYTBLEDAYS, 180);
        deflt.put(ConfigConstants.MISCMYTABLEMOVEINTERVALDAYS, 5);
        deflt.put(ConfigConstants.MISCMYTABLEINTERVALDAYS, 1);
        deflt.put(ConfigConstants.MISCMYEQUALIZE, Boolean.TRUE);
        deflt.put(ConfigConstants.MISCMYGRAPHEQUALIZE, Boolean.TRUE);
        deflt.put(ConfigConstants.MISCMYGRAPHEQUALIZEUNIFY, Boolean.TRUE);
        deflt.put(ConfigConstants.TESTINDICATORRECOMMENDERCOMPLEXFUTUREDAYS, 10);
        deflt.put(ConfigConstants.TESTINDICATORRECOMMENDERCOMPLEXINTERVALDAYS, 5);
        deflt.put(ConfigConstants.TESTINDICATORRECOMMENDERSIMPLEFUTUREDAYS, 10);
        deflt.put(ConfigConstants.TESTINDICATORRECOMMENDERSIMPLEINTERVALDAYS, 5);
        deflt.put(ConfigConstants.TESTRECOMMENDINTERVALTIMES, 10);
        deflt.put(ConfigConstants.TESTRECOMMENDITERATIONS, 100);
        deflt.put(ConfigConstants.TESTRECOMMENDPERIOD, CategoryConstants.PRICE);
        deflt.put(ConfigConstants.TESTRECOMMENDFACTOR, 10);
        deflt.put(ConfigConstants.EVOLUTIONGENERATIONS, 2);
        deflt.put(ConfigConstants.EVOLUTIONCHILDREN, 4);
        //deflt.put(ConfigConstants.EVOLUTION, Boolean.FALSE);
        deflt.put(ConfigConstants.EVOLUTION, "");
        deflt.put(ConfigConstants.EVOLUTIONELITE, 1);
        deflt.put(ConfigConstants.EVOLUTIONELITECLONEANDMUTATE, 0);
        deflt.put(ConfigConstants.EVOLUTIONMUTATE, 1);
        deflt.put(ConfigConstants.EVOLUTIONCROSSOVER, 1);
        deflt.put(ConfigConstants.EVOLUTIONGENERATIONCREATE, 0);
        deflt.put(ConfigConstants.EVOLUTIONSELECT, 16);
        deflt.put(ConfigConstants.AGGREGATORS, Boolean.TRUE);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDER, Boolean.TRUE);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLE, Boolean.TRUE);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACD, Boolean.TRUE);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUY, null);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUYWEIGHTHISTOGRAM, 40);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUYWEIGHTHISTOGRAMDELTA, 20);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUYWEIGHTMOMENTUM, 20);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUYWEIGHTMOMENTUMDELTA, 20);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELL, null);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELLWEIGHTHISTOGRAM, 40);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELLWEIGHTHISTOGRAMDELTA, 20);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELLWEIGHTMOMENTUM, 20);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELLWEIGHTMOMENTUMDELTA, 20);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSI, Boolean.TRUE);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSISELL, null);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSIBUYWEIGHTRSI, 20);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSIBUYWEIGHTRSIDELTA, 20);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSISELL, null);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSISELLWEIGHTRSI, 20);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSISELLWEIGHTRSIDELTA, 20);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEX, Boolean.TRUE);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACD, Boolean.TRUE);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUY, null);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUYWEIGHTHISTOGRAMNODE, json);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUYWEIGHTHISTOGRAMDELTANODE, json);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUYWEIGHTMOMENTUMNODE, json);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUYWEIGHTMOMENTUMDELTANODE, json);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELL, null);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELLWEIGHTHISTOGRAMNODE, json);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELLWEIGHTHISTOGRAMDELTANODE, json);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELLWEIGHTMOMENTUMNODE, json);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELLWEIGHTMOMENTUMDELTANODE, json);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSI, Boolean.TRUE);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSIBUY, null);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSIBUYWEIGHTRSINODE, json);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSIBUYWEIGHTRSIDELTANODE, json);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSISELL, null);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSISELLWEIGHTRSINODE, json);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSISELLWEIGHTRSIDELTANODE, json);
        deflt.put(ConfigConstants.AGGREGATORSINDICATOR, Boolean.FALSE);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORMACD, Boolean.FALSE);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORRSI, Boolean.FALSE);
        deflt.put(ConfigConstants.AGGREGATORSINDICATOREXTRAS, "");
        deflt.put(ConfigConstants.AGGREGATORSINDICATOREXTRASDELTAS, 2);
        deflt.put(ConfigConstants.AGGREGATORSINDICATOREXTRASMACD, Boolean.FALSE);
        deflt.put(ConfigConstants.AGGREGATORSINDICATOREXTRASRSI, Boolean.FALSE);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORFUTUREDAYS, 10);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORINTERVALDAYS, 1);
        deflt.put(ConfigConstants.AGGREGATORSINDICATORTHRESHOLD, 0);
        deflt.put(ConfigConstants.AGGREGATORSMLMACD, Boolean.TRUE);
    }

    //private final static String json = "{\"_class\": \"roart.calculate.CalcMACDNode\", \"className\":\"CalcMacdNode\",\"minMutateThresholdRange\":-5.0,\"maxMutateThresholdRange\":5.0,\"threshold\":-2.476814906438654,\"useminmaxthreshold\":true,\"usethreshold\":false,\"divideminmaxthreshold\":true,\"weight\":31.0,\"changeSignWhole\":false,\"useMax\":false}";
    private final static String json = null; // "{\"_class\": \"roart.calculate.CalcMACDNode\", \"className\":\"CalcMacdNode\",\"minMutateThresholdRange\":-5.0,\"maxMutateThresholdRange\":5.0,\"threshold\":-2.476814906438654,\"useminmaxthreshold\":true,\"usethreshold\":false,\"weight\":31.0,\"useMax\":false}";

    public static Map<String, String> text = new HashMap();

    public static void makeTextMap() {
        if (!text.isEmpty()) {
            return;
        }
        text.put(ConfigConstants.DATABASEMAXHOLES, "Max number of holes/NaN to be filled");
        text.put(ConfigConstants.DATABASESPARK, "Enable Spark Database backend");
        text.put(ConfigConstants.DATABASESPARKSPARKMASTER, "Database Spark Master");
        text.put(ConfigConstants.DATABASEHIBERNATE, "Enable Hibernate Database backend");
        text.put(ConfigConstants.MACHINELEARNING, "Enable machine learning");
        text.put(ConfigConstants.MACHINELEARNINGMP, "Enable machine learning multiprocessing");
        text.put(ConfigConstants.MACHINELEARNINGMPCPUFRACTION, "Machine learning multiprocessing total cpu fraction");
        text.put(ConfigConstants.MACHINELEARNINGSPARKML, "Enable Spark ML");
        text.put(ConfigConstants.MACHINELEARNINGSPARMMLSPARKMASTER, "Machine Learning Spark Master");
        text.put(ConfigConstants.MACHINELEARNINGSPARKMLMCP, "Enable Spark ML MCP");
        text.put(ConfigConstants.MACHINELEARNINGSPARKMLLR, "Enable Spark ML LR");
        text.put(ConfigConstants.MACHINELEARNINGTENSORFLOW, "Enable Tensorflow");
        text.put(ConfigConstants.MACHINELEARNINGTENSORFLOWDNN, "Enable Tensorflow DNN");
        text.put(ConfigConstants.MACHINELEARNINGTENSORFLOWL, "Enable Tensorflow L");
        text.put(ConfigConstants.MACHINELEARNINGTENSORFLOWSERVER, "Tensorflow Server");
        text.put(ConfigConstants.INDICATORS, "Enable indicators");
        text.put(ConfigConstants.INDICATORSMOVE, "Enable move indicator");
        text.put(ConfigConstants.INDICATORSMACD, "Enable MACD indicator");
        text.put(ConfigConstants.INDICATORSMACDMACDHISTOGRAMDELTA, "Enable MACD histogram delta");
        text.put(ConfigConstants.INDICATORSMACDMACHHISTOGRAMDELTADAYS, "MACD histogram delta days");

        text.put(ConfigConstants.INDICATORSMACDMACDMOMENTUMDELTA, "Enable MACD momentum delta");
        text.put(ConfigConstants.INDICATORSMACDACDMOMENTUMDELTADAYS, "MACD momentum delta days");
        text.put(ConfigConstants.INDICATORSMACDRECOMMEND, "Enable MACD buy/sell recommendation");
        text.put(ConfigConstants.INDICATORSMACDRECOMMENDBUY, "Buy");
        text.put(ConfigConstants.INDICATORSMACDRECOMMENDBUYWEIGHTHISTOGRAM, "Buy weight histogram");
        text.put(ConfigConstants.INDICATORSMACDRECOMMENDBUYWEIGHTHISTOGRAMDELTA, "Buy weight histogram delta");
        text.put(ConfigConstants.INDICATORSMACDRECOMMENDBUYWEIGHTMOMENTUM, "Buy weight momentum");
        text.put(ConfigConstants.INDICATORSMACDRECOMMENDBUYWEIGHTMOMENTUMDELTA, "Buy weight momentum delta");
        text.put(ConfigConstants.INDICATORSMACDRECOMMENDSELL, "Sell");
        text.put(ConfigConstants.INDICATORSMACDRECOMMENDSELLWEIGHTHISTOGRAM, "Sell weight histogram");
        text.put(ConfigConstants.INDICATORSMACDRECOMMENDSELLWEIGHTHISTOGRAMDELTA, "Sell weight histogram delta");
        text.put(ConfigConstants.INDICATORSMACDRECOMMENDSELLWEIGHTMOMENTUM, "Sell weight momentum");
        text.put(ConfigConstants.INDICATORSMACDRECOMMENDSELLWEIGHTMOMENTUMDELTA, "Sell weight momentum delta");
        text.put(ConfigConstants.INDICATORSMACDMACHINELEARNING, "Enable indicator MACD machine learning");
        text.put(ConfigConstants.INDICATORSMACDMACHINELEARNINGMOMENTUMML, "Enable indicator MACD momentum machine learning");
        text.put(ConfigConstants.INDICATORSMACDMACHINELEARNINGHISTOGRAMML, "Enable indicator MACD histogram machine learning");
        text.put(ConfigConstants.INDICATORSMACDDAYSBEFOREZERO, "Days before zero");
        text.put(ConfigConstants.INDICATORSMACDDAYSAFTERZERO, "Days after zero");
        text.put(ConfigConstants.INDICATORSRSI, "Enable indicator RSI");
        text.put(ConfigConstants.INDICATORSRSIDELTA, "Enable indicator RSI delta");
        text.put(ConfigConstants.INDICATORSRSIDELTADAYS, "RSI delta days");
        text.put(ConfigConstants.INDICATORSRSIRECOMMEND, "Enable buy/sell indicator RSI");
        text.put(ConfigConstants.INDICATORSRSIRECOMMENDBUY, "RSI buy");
        text.put(ConfigConstants.INDICATORSRSIRECOMMENDBUYWEIGHT, "RSI buy weight");
        text.put(ConfigConstants.INDICATORSRSIRECOMMENDBUYWEIGHTDELTA, "RSI delta buy weight");
        text.put(ConfigConstants.INDICATORSRSIRECOMMENDSELL, "RSI sell");
        text.put(ConfigConstants.INDICATORSRSIRECOMMENDSELLWEIGHT, "RSI sell weight");
        text.put(ConfigConstants.INDICATORSRSIRECOMMENDSELLWEIGHTDELTA, "RSI delta sell weight");
        text.put(ConfigConstants.INDICATORSSTOCHRSI, "Enable indicator STOCH RSI");
        text.put(ConfigConstants.INDICATORSSTOCHRSIDELTA, "Enable indicator STOCH RSI delta");
        text.put(ConfigConstants.INDICATORSSTOCHRSIDELTADAYS, "STOCH RSI delta days");
        text.put(ConfigConstants.INDICATORSCCI, "Enable indicator CCI");
        text.put(ConfigConstants.INDICATORSCCIDELTA, "Enable indicator CCI delta");
        text.put(ConfigConstants.INDICATORSCCIDELTADAYS, "CCI delta days");
        text.put(ConfigConstants.INDICATORSATR, "Enable indicator ATR");
        text.put(ConfigConstants.INDICATORSATRDELTA, "Enable indicator ATR delta");
        text.put(ConfigConstants.INDICATORSATRDELTADAYS, "ATR delta days");
        text.put(ConfigConstants.INDICATORSSTOCH, "Enable indicator STOCH");
        text.put(ConfigConstants.INDICATORSSTOCHSTOCHDELTA, "Enable indicator STOCH delta");
        text.put(ConfigConstants.INDICATORSSTOCHSTOCHDELTADAYS, "STOCH delta days");
        text.put(ConfigConstants.PREDICTORS, "Enable predictors");
        text.put(ConfigConstants.PREDICTORSLSTM, "Enable LSTM predictor");
        text.put(ConfigConstants.PREDICTORSLSTMEPOCHS, "LSTM epochs");
        text.put(ConfigConstants.PREDICTORSLSTMHORIZON, "LSTM horizon");
        text.put(ConfigConstants.PREDICTORSLSTMWINDOWSIZE, "LSTM windowsize");
        text.put(ConfigConstants.MISC, "Misc");
        text.put(ConfigConstants.MISCPERCENTIZEPRICEINDEX, "Enable turning price/index into percent based on first date");
        text.put(ConfigConstants.MISCMLSTATS, "Enable ML stats for time usage");
        text.put(ConfigConstants.MISCOTHERSTATS, "Enable other stat pages");
        text.put(ConfigConstants.MISCMYDAYS, "Number of days to display");
        text.put(ConfigConstants.MISCMYTOPBOTTOM, "Number of items to display");
        text.put(ConfigConstants.MISCMYTBLEDAYS, "Table days");
        text.put(ConfigConstants.MISCMYTABLEMOVEINTERVALDAYS, "Interval days for table move");
        text.put(ConfigConstants.MISCMYTABLEINTERVALDAYS, "Table interval days");
        text.put(ConfigConstants.MISCMYEQUALIZE, "Enable equalizing");
        text.put(ConfigConstants.MISCMYGRAPHEQUALIZE, "Enable graph equalizing");
        text.put(ConfigConstants.MISCMYGRAPHEQUALIZEUNIFY, "Enable unified graph equalizing");
        text.put(ConfigConstants.TESTINDICATORRECOMMENDERSIMPLEFUTUREDAYS, "Test simple recommender future days");
        text.put(ConfigConstants.TESTINDICATORRECOMMENDERSIMPLEINTERVALDAYS, "Test simple recommender interval days");
        text.put(ConfigConstants.TESTINDICATORRECOMMENDERCOMPLEXFUTUREDAYS, "Test complex recommender future days");
        text.put(ConfigConstants.TESTINDICATORRECOMMENDERCOMPLEXINTERVALDAYS, "Test complex recommender interval days");
        text.put(ConfigConstants.TESTRECOMMENDINTERVALTIMES, "Deprecated Test recommender interval times");
        text.put(ConfigConstants.TESTRECOMMENDITERATIONS, "Deprecated Test recommender iterations");
        text.put(ConfigConstants.TESTRECOMMENDPERIOD, "Deprecated Test recommender period");
        text.put(ConfigConstants.EVOLUTION, "Evolution enable");
        text.put(ConfigConstants.EVOLUTIONGENERATIONS, "Evolution generations");
        text.put(ConfigConstants.EVOLUTIONCHILDREN, "Deprecated Evolution children");
        text.put(ConfigConstants.EVOLUTIONCROSSOVER, "Evolution crossover");
        text.put(ConfigConstants.EVOLUTIONGENERATIONCREATE, "Evolution create random in a generation");
        text.put(ConfigConstants.EVOLUTIONELITE, "Evolution elite");
        text.put(ConfigConstants.EVOLUTIONELITECLONEANDMUTATE, "Evolution elite clone and mutate");
        text.put(ConfigConstants.EVOLUTIONSELECT, "Evolution select population");
        text.put(ConfigConstants.EVOLUTIONMUTATE, "Evolution mutate");
        text.put(ConfigConstants.AGGREGATORS, "Enable aggregators");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDER, "Enable aggregated recommender");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLE, "Enable aggregated recommender simple");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACD, "Enable aggregated recommender simple MACD");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUY, "Buy");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUYWEIGHTHISTOGRAM, "Buy weight histogram");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUYWEIGHTHISTOGRAMDELTA, "Buy weight histogram delta");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUYWEIGHTMOMENTUM, "Buy weight momentum");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDBUYWEIGHTMOMENTUMDELTA ,"Buy weight momentum delta");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELL ,"Sell");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELLWEIGHTHISTOGRAM ,"Sell weight histogram");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELLWEIGHTHISTOGRAMDELTA, "Sell weight histogram delta");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELLWEIGHTMOMENTUM ,"Sell weight momentum");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLEMACDSELLWEIGHTMOMENTUMDELTA,"Sell weight momentum delta");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSI, "Enable aggregated recommender simple RSI");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSIBUY, "Buy");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSIBUYWEIGHTRSI, "Buy weight RSI");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSIBUYWEIGHTRSIDELTA, "Buy weight RSI delta");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSISELL, "Sell");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSISELLWEIGHTRSI, "Sell weight RSI");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERSIMPLERSISELLWEIGHTRSIDELTA, "Sell weight RSI delta");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEX, "Enable aggregated recommender complex");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACD, "Enable aggregated recommender complex MACD");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUY, "Buy");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUYWEIGHTHISTOGRAMNODE, "Buy weight histogram node");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUYWEIGHTHISTOGRAMDELTANODE, "Buy weight histogram delta node");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUYWEIGHTMOMENTUMNODE, "Buy weight momentum node");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDBUYWEIGHTMOMENTUMDELTANODE ,"Buy weight momentum delta node");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELL, "Sell");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELLWEIGHTHISTOGRAMDELTANODE, "Sell weight histogram delta node");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELLWEIGHTMOMENTUMNODE ,"Sell weight momentum node");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELLWEIGHTMOMENTUMDELTANODE,"Sell weight momentum delta node");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSIBUYWEIGHTRSINODE, "Buy weight RSI node");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSI, "Enable aggregated recommender complex RSI");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSIBUY, "Buy");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSIBUYWEIGHTRSIDELTANODE, "Buy weight RSI delta node");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXMACDSELLWEIGHTHISTOGRAMNODE ,"Sell weight histogram node");		
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSISELL, "Sell");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSISELLWEIGHTRSINODE, "Sell weight RSI node");
        text.put(ConfigConstants.AGGREGATORSINDICATORRECOMMENDERCOMPLEXRSISELLWEIGHTRSIDELTANODE, "Sell weight RSI delta node");
        text.put(ConfigConstants.AGGREGATORSINDICATOR, "ML indicator enable");
        text.put(ConfigConstants.AGGREGATORSINDICATORMACD, "ML indicator MACD enable");
        text.put(ConfigConstants.AGGREGATORSINDICATORRSI, "ML indicator RSI enable");
        text.put(ConfigConstants.AGGREGATORSINDICATOREXTRAS, "ML indicator extras");
        text.put(ConfigConstants.AGGREGATORSINDICATOREXTRASDELTAS, "ML indicator extras delta days");
        text.put(ConfigConstants.AGGREGATORSINDICATOREXTRASMACD, "ML indicator extras use MACD result");
        text.put(ConfigConstants.AGGREGATORSINDICATOREXTRASRSI, "ML indicator extras use RSI result");
        text.put(ConfigConstants.AGGREGATORSINDICATORFUTUREDAYS, "ML indicator days in the future for threshold");
        text.put(ConfigConstants.AGGREGATORSINDICATORINTERVALDAYS, "ML indicator days in the future interval");
        text.put(ConfigConstants.AGGREGATORSINDICATORTHRESHOLD, "ML indicator threshold for classifier");
        text.put(ConfigConstants.AGGREGATORSMLMACD, "MLMACD aggreagator enable");

    }


}
