package roart.iclij.config;

public class IclijConfigConstants {
    public static final String EVOLVE = "evolve";
    public static final String EVOLVEINDICATORRECOMMENDER = "evolve.indicatorrecommender";
    public static final String EVOLVEINDICATORRECOMMENDEREVOLUTIONCONFIG = "evolve.indicatorrecommender.evolutionconfig";
    public static final String EVOLVEML = "evolve.ml";
    public static final String EVOLVEMLMLCONFIG = "evolve.ml.mlconfig";
    public static final String EVOLVEMLEVOLUTIONCONFIG = "evolve.ml.evolutionconfig";
    public static final String EVOLVEMLTENSORFLOWSERVER = "evolve.ml.tensorflowserver";
    public static final String MISCSHUTDOWNHOUR = "misc.shutdownhour";
    public static final String MPSERVERCPU = "mp.server.cpu";
    public static final String MPCLIENTCPU = "mp.client.cpu";
    public static final String FINDPROFITAUTORUN = "findprofit.autorun";
    public static final String FINDPROFITRECOMMENDER = "findprofit.recommender";
    public static final String FINDPROFITMLMACD = "findprofit.mlmacd";
    public static final String FINDPROFITMLMACDEVOLUTIONCONFIG = "findprofit.mlmacd.evolutionconfig";
    public static final String FINDPROFITMLMACDMLCONFIG = "findprofit.mlmacd.mlconfig";
    public static final String FINDPROFITMLRSI = "findprofit.mlrsi";
    public static final String FINDPROFITMLRSIEVOLUTIONCONFIG = "findprofit.mlrsi.evolutionconfig";
    public static final String FINDPROFITMLRSIMLCONFIG = "findprofit.mlrsi.mlconfig";
    public static final String FINDPROFITMLINDICATOR = "findprofit.mlindicator";
    public static final String FINDPROFITMLINDICATOREVOLUTIONCONFIG = "findprofit.mlindicator.evolutionconfig";
    public static final String FINDPROFITMLINDICATORMLCONFIG = "findprofit.mlindicator.mlconfig";
    public static final String FINDPROFITPREDICTOR = "findprofit.predictor";
    public static final String FINDPROFITPREDICTOREVOLUTIONCONFIG = "findprofit.predictor.evolutionconfig";
    public static final String FINDPROFITPREDICTORMLCONFIG = "findprofit.predictor.mlconfig";
    public static final String IMPROVEPROFITAUTORUN = "improveprofit.autorun";
    public static final String IMPROVEPROFITFITNESSMINIMUM = "improveprofit.fitnessminimum";
    public static final String IMPROVEPROFITRECOMMENDER = "improveprofit.recommender";
    public static final String IMPROVEPROFITMLMACD = "improveprofit.mlmacd";
    public static final String IMPROVEPROFITMLMACDEVOLUTIONCONFIG = "improveprofit.mlmacd.evolutionconfig";
    public static final String IMPROVEPROFITMLMACDMLCONFIG = "improveprofit.mlmacd.mlconfig";
    public static final String IMPROVEPROFITMLRSI = "improveprofit.mlrsi";
    public static final String IMPROVEPROFITMLRSIEVOLUTIONCONFIG = "improveprofit.mlrsi.evolutionconfig";
    public static final String IMPROVEPROFITMLRSIMLCONFIG = "improveprofit.mlrsi.mlconfig";
    public static final String IMPROVEPROFITMLINDICATOR = "improveprofit.mlindicator";
    public static final String IMPROVEPROFITMLINDICATOREVOLUTIONCONFIG = "improveprofit.mlindicator.evolutionconfig";
    public static final String IMPROVEPROFITMLINDICATORMLCONFIG = "improveprofit.mlindicator.mlconfig";
    public static final String IMPROVEPROFITPREDICTOR = "improveprofit.predictor";
    public static final String IMPROVEPROFITPREDICTOREVOLUTIONCONFIG = "improveprofit.predictor.evolutionconfig";
    public static final String IMPROVEPROFITPREDICTORMLCONFIG = "improveprofit.predictor.mlconfig";
    public static final String SINGLEMARKETEVOLVEFIRSTONLY = "singlemarket.evolvefirstonly";
    public static final String SINGLEMARKETLOOPS = "singlemarket.loops";
    public static final String SINGLEMARKETLOOPINTERVAL = "singlemarket.loopinterval";
    public static final String VERIFICATION = "verification";
    public static final String VERIFICATIONSAVE = "verification.save";
    public static final String VERIFICATIONDAYS = "verification.days";
    public static final String VERIFICATIONEVOLVEFIRSTONLY = "verification.evolvefirstonly";
    public static final String VERIFICATIONLOOPS = "verification.loops";
    public static final String VERIFICATIONLOOPINTERVAL = "verification.loopinterval";
    public static final String VERIFICATIONRECOMMENDERTOPBOTTOM = "verification.recommender.topbottom";
    @Deprecated
    public static final String VERIFICATIONIMPROVEPROFIT = "verification.improveprofit";
    public static final String MARKETSMARKETLISTMARKET2 = "markets.marketlist.market";
    public static final String MARKETSTRADEMARKETSMARKET2 = "markets.trademarkets.trademarket";
    public static final String MARKETSIMPORTANTSIMPORTANT2 = "markets.importants.important";
    public static final String MARKETSMARKETLISTMARKET = "markets.marketlist.market[@id]";
    public static final String MARKETSMARKETLISTMARKETCONFIG = "markets.marketlist.market[@id].config";
    public static final String MARKETSMARKETLISTMARKETFILTER = "markets.marketlist.market[@id].filter";
    //public static final String MARKETSMARKETLISTMARKETEVOLUTIONCONFIG = "markets.marketlist.market[@id].evolutionconfig";
    public static final String MARKETSMARKETLISTMARKETMLCONFIG = "markets.marketlist.market[@id].mlconfig";
    @Deprecated
    public static final String MARKETSFILTERMARKETSMARKET = "markets.filtermarkets.filtermarket[@id]";
    public static final String MARKETSIMPORTANTSIMPORTANT = "markets.importants.important[@id]";
}
