apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
  - image: dbclone
    context: ../../..
    docker:
      dockerfile: docker/cloud/dbclone/Dockerfile
      buildArgs:
        mydump: '{{.MYDUMP}}'
        mydbserver: '{{.MYDBSERVER}}'
deploy:
  kubectl:
    manifests:
    - dbclone/deployment.yaml
    - postgresql/deployment.yaml
