apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: core
build:
  artifacts:
  - image: core
    context: ../../..
    docker:
      dockerfile: docker/cloud/core/Dockerfile
      buildArgs:
        mywebport: "80"
        mydbserver: '{{.MYDBSERVER}}'
        myconfig: '{{.MYCONFIG}}'
        myenv: '{{.MYENV}}'
  - image: icore
    context: ../../..
    docker:
      dockerfile: docker/cloud/iclij-core/Dockerfile
      buildArgs:
        myserver: '{{.CORESERVER}}'
        mywebport: "80"
        mydbserver: '{{.MYDBSERVER}}'
        myconfig: '{{.MYICONFIG}}'
        myenv: '{{.MYIENV}}'
deploy:
  kubectl:
    manifests:
    - core/deployment.yaml
    - icore/deployment.yaml
