apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
  - image: tensorflowdata
    context: ../../..
    docker:
      dockerfile: docker/cloud/tensorflowdata/Dockerfile
      buildArgs:
        mydata: '{{.MYTFDATA}}'
  - image: tensorflow
    context: ../../..
    docker:
      dockerfile: docker/cloud/tensorflow/Dockerfile
  - image: pytorchdata
    context: ../../..
    docker:
      dockerfile: docker/cloud/pytorchdata/Dockerfile
      buildArgs:
        mydata: '{{.MYPTDATA}}'
  - image: pytorch
    context: ../../..
    docker:
      dockerfile: docker/cloud/pytorch/Dockerfile
deploy:
  kubectl:
    manifests:
    - tensorflowdata/deployment.yaml
    - pytorchdata/deployment.yaml
    - tensorflow/deployment.yaml
    - pytorch/deployment.yaml
