apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
  - image: pdfred
    context: ../../..
    docker:
      dockerfile: docker/cloud/pdfred/Dockerfile
deploy:
  kubectl:
    manifests:
    - pdfred/deployment.yaml
    - postgresql/deployment.yaml
