apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
  - image: webr
    context: ../../..
    docker:
      dockerfile: docker/cloud/webr/Dockerfile
      buildArgs:
        docroot: '{{.WEBRDOCROOT}}'
        myserver: '{{.MYSERVER}}'
        myport: '{{.MYPORT}}'
        mywebport: "80"
  - image: iwebr
    context: ../../..
    docker:
      dockerfile: docker/cloud/webr/Dockerfile
      buildArgs:
        docroot: '{{.IWEBRDOCROOT}}'
        myiserver: '{{.MYISERVER}}'
        mypiort: '{{.MYIPORT}}'
        myserver: '{{.MYSERVER}}'
        mywebport: "80"
deploy:
  kubectl:
    manifests:
    - webr/deployment.yaml
    - iwebr/deployment.yaml
